### ISSUE TITLE
How to compile for Windows 10?

### ISSUE THREAD

**Issue by wgprojects** [yellingintothefan/weaver#1]
Hi there. I'm trying to compile your code using Cygwin on Win10.
Apparently Cygwin doesn't include ComSpec like the makefile expects.

Do you have any suggestions for a Windows build? Thanks!

**Comment by glouw** [comment]
Check under the release section. There's a weaver1.2 zip with everything you need.

Otherwise:

1. install mingw32 for windows (not through cygwin).

2. Add C:\MinGW\bin to path.

3. Extract the weaver repo to your desktop. Download and extract to your desktop SDL2_image-2.0.2 and SDL2-2.0.7 dev folders. Find them here:

    https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.2-mingw.tar.gz

    https://www.libsdl.org/release/SDL2-devel-2.0.7-mingw.tar.gz

4. Open cmd.exe

    cd \to\the\weaver-1.2\folder

    mingw32-make

5. With the .exe built you will have to copy over all the .dlls to where the .exe is. Find the .dlls here:

    SDL2_image-2.0.2\i686-w64-mingw32\bin
    SDL2-2.0.7\i686-w64-mingw32\bin

6. weaver.exe path\to\your\image 80

You can play with the threshold value. The lower, the better.

**Comment by wgprojects** [comment]
Thanks! I think the instructions will be sufficient, but (and I feel daft having to ask...) but where is the 'release section'?
It's not in the code, or on a branch...

**Comment by glouw** [comment]
https://github.com/yellingintothefan/weaver/releases

You'll want the zip file attached, It has the compiled exe and all .dll deps included

**Comment by wgprojects** [comment]
I'm not sure how I missed that. 
Thanks again, and nice work!
